name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  lint:
    uses: cosmicmind/github-actions/.github/workflows/lint.yml@release
  codeql:
    uses: cosmicmind/github-actions/.github/workflows/codeql.yml@release
  build:
    uses: cosmicmind/github-actions/.github/workflows/lib-dev.yml@release
  test:
    uses: cosmicmind/github-actions/.github/workflows/lib-test.yml@release
