name: Feature Push

on:
  push:
    branches-ignore:
      - develop
      - release

jobs:
  lint:
    uses: cosmicmind/actions/.github/workflows/lint-code.yml@release

  build:
    needs:
      - lint
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: develop
      NODE_ENV: development
      VITE_MODE: development

  test:
    needs:
      - build
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: develop
      NODE_ENV: development
      VITE_MODE: test

  codeql:
    needs:
      - test
    uses: cosmicmind/actions/.github/workflows/codeql.yml@release
