name: Release Push

on:
  push:
    branches:
      - release

jobs:
  lint:
    uses: cosmicmind/actions/.github/workflows/lint-code.yml@release

  build:
    needs:
      - lint
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: release
      NODE_ENV: production
      VITE_MODE: production

  test:
    needs:
      - build
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: test
      NODE_ENV: production
      VITE_MODE: test

  codeql:
    needs:
      - test
    uses: cosmicmind/actions/.github/workflows/codeql.yml@release

  publish:
    needs:
      - codeql
    uses: cosmicmind/actions/.github/workflows/publish-package.yml@release
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}