name: Release Push

on:
  push:
    branches:
      - release

jobs:
  lint:
    uses: cosmicmind/github-actions/.github/workflows/lint.yml@release
  codeql:
    needs: lint
    uses: cosmicmind/github-actions/.github/workflows/codeql.yml@release
  build:
    needs: codeql
    uses: cosmicmind/github-actions/.github/workflows/lib-release.yml@release
  test:
    needs: build
    uses: cosmicmind/github-actions/.github/workflows/lib-test.yml@release
